### ISSUE TITLE
enc_commutation 1:

### ISSUE THREAD

**Issue by gauix4** [makertum/Trinamic_TMC2130#1]
enc_commutation
1: Enable commutation by full step encoder (DCIN_CFG5 = ENC_A, DCEN_CFG4 = ENC_B)

hello
you have more details on this one because I not find
thanks ;)

**Comment by makertum** [comment]
Hi, I asked Trinamic. This seems to be a customer application specific feature that turns the motor into a freerunning mode where it just spins as fast as it can.

It is NOT:
- a feature to increase resolution 
- a feature to increase accuracy
- a feature that turns the stepper motor into a quasi-servo

Best,
Moritz
