### ISSUE TITLE
Compilation terminated

### ISSUE THREAD

**Issue by DaGov** [makertum/Trinamic_TMC2130#3]
I copied 3 files (.h and .cpp and registers.h) in Marlin fork folder.
After this I compile Marlin. Fatal error: Trinamic_TMC2130.h: No such file or directory. In Marlin.ino.
Get instruction, please.

**Comment by makertum** [comment]
Hi, I think you need to install the library in your arduino directory. Please check google (or arduino.cc) on how to install the library on your operating system.

**Comment by DaGov** [comment]
Hi! How I can change CS pins of drivers?
