### ISSUE TITLE
Trinamic_TMC2130::set_mres input parameter type should be uint16_t, not uint8_t

### ISSUE THREAD

**Issue by dmitryplatonov** [makertum/Trinamic_TMC2130#5]
Value 256 is out of range for uint8_t, so setting microstepping to 256 will have unpredictable result, as no case statement will be executed. Trivial patch is included.
Perhaps better solution will be to have defines for microstepping values and also include default case statement to handle erroneous input parameters. 
[set_mres.patch.txt](https://github.com/makertum/Trinamic_TMC2130/files/583179/set_mres.patch.txt)

**Comment by makertum** [comment]
fixed, thanks!
